name: Django Tests

on: [pull_request, push]
jobs: 
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install flake8
      - run: pip install -r requirements.txt
      - run: pip install postgresql
      - run: createdb ecom_app_db
      - run: python manage.py test
      - run: flake8